// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: newp/ml/ml.proto

package ml1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DetectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       int64                  `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	DirPath       string                 `protobuf:"bytes,2,opt,name=dir_path,json=dirPath,proto3" json:"dir_path,omitempty"`
	Targets       []string               `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionRequest) Reset() {
	*x = DetectionRequest{}
	mi := &file_newp_ml_ml_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionRequest) ProtoMessage() {}

func (x *DetectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_ml_ml_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionRequest.ProtoReflect.Descriptor instead.
func (*DetectionRequest) Descriptor() ([]byte, []int) {
	return file_newp_ml_ml_proto_rawDescGZIP(), []int{0}
}

func (x *DetectionRequest) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *DetectionRequest) GetDirPath() string {
	if x != nil {
		return x.DirPath
	}
	return ""
}

func (x *DetectionRequest) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type DetectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       int64                  `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	ResultPath    string                 `protobuf:"bytes,2,opt,name=result_path,json=resultPath,proto3" json:"result_path,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	ClassCounts   []*ClassCount          `protobuf:"bytes,4,rep,name=class_counts,json=classCounts,proto3" json:"class_counts,omitempty"` // [{"person": 3}, {"car": 2}]
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TotalObjects  int32                  `protobuf:"varint,6,opt,name=total_objects,json=totalObjects,proto3" json:"total_objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetectionResponse) Reset() {
	*x = DetectionResponse{}
	mi := &file_newp_ml_ml_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionResponse) ProtoMessage() {}

func (x *DetectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_ml_ml_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectionResponse.ProtoReflect.Descriptor instead.
func (*DetectionResponse) Descriptor() ([]byte, []int) {
	return file_newp_ml_ml_proto_rawDescGZIP(), []int{1}
}

func (x *DetectionResponse) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *DetectionResponse) GetResultPath() string {
	if x != nil {
		return x.ResultPath
	}
	return ""
}

func (x *DetectionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DetectionResponse) GetClassCounts() []*ClassCount {
	if x != nil {
		return x.ClassCounts
	}
	return nil
}

func (x *DetectionResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *DetectionResponse) GetTotalObjects() int32 {
	if x != nil {
		return x.TotalObjects
	}
	return 0
}

type ClassCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassName     string                 `protobuf:"bytes,1,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassCount) Reset() {
	*x = ClassCount{}
	mi := &file_newp_ml_ml_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassCount) ProtoMessage() {}

func (x *ClassCount) ProtoReflect() protoreflect.Message {
	mi := &file_newp_ml_ml_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassCount.ProtoReflect.Descriptor instead.
func (*ClassCount) Descriptor() ([]byte, []int) {
	return file_newp_ml_ml_proto_rawDescGZIP(), []int{2}
}

func (x *ClassCount) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

func (x *ClassCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_newp_ml_ml_proto protoreflect.FileDescriptor

const file_newp_ml_ml_proto_rawDesc = "" +
	"\n" +
	"\x10newp/ml/ml.proto\x12\x04grps\"b\n" +
	"\x10DetectionRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\x03R\aqueryId\x12\x19\n" +
	"\bdir_path\x18\x02 \x01(\tR\adirPath\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\"\xe8\x01\n" +
	"\x11DetectionResponse\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\x03R\aqueryId\x12\x1f\n" +
	"\vresult_path\x18\x02 \x01(\tR\n" +
	"resultPath\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x123\n" +
	"\fclass_counts\x18\x04 \x03(\v2\x10.grps.ClassCountR\vclassCounts\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12#\n" +
	"\rtotal_objects\x18\x06 \x01(\x05R\ftotalObjects\"A\n" +
	"\n" +
	"ClassCount\x12\x1d\n" +
	"\n" +
	"class_name\x18\x01 \x01(\tR\tclassName\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2M\n" +
	"\bDetector\x12A\n" +
	"\x0eImageDetection\x12\x16.grps.DetectionRequest\x1a\x17.grps.DetectionResponseB\x12Z\x10sirius.ml.v1;ml1b\x06proto3"

var (
	file_newp_ml_ml_proto_rawDescOnce sync.Once
	file_newp_ml_ml_proto_rawDescData []byte
)

func file_newp_ml_ml_proto_rawDescGZIP() []byte {
	file_newp_ml_ml_proto_rawDescOnce.Do(func() {
		file_newp_ml_ml_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_newp_ml_ml_proto_rawDesc), len(file_newp_ml_ml_proto_rawDesc)))
	})
	return file_newp_ml_ml_proto_rawDescData
}

var file_newp_ml_ml_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_newp_ml_ml_proto_goTypes = []any{
	(*DetectionRequest)(nil),  // 0: grps.DetectionRequest
	(*DetectionResponse)(nil), // 1: grps.DetectionResponse
	(*ClassCount)(nil),        // 2: grps.ClassCount
}
var file_newp_ml_ml_proto_depIdxs = []int32{
	2, // 0: grps.DetectionResponse.class_counts:type_name -> grps.ClassCount
	0, // 1: grps.Detector.ImageDetection:input_type -> grps.DetectionRequest
	1, // 2: grps.Detector.ImageDetection:output_type -> grps.DetectionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_newp_ml_ml_proto_init() }
func file_newp_ml_ml_proto_init() {
	if File_newp_ml_ml_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_newp_ml_ml_proto_rawDesc), len(file_newp_ml_ml_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newp_ml_ml_proto_goTypes,
		DependencyIndexes: file_newp_ml_ml_proto_depIdxs,
		MessageInfos:      file_newp_ml_ml_proto_msgTypes,
	}.Build()
	File_newp_ml_ml_proto = out.File
	file_newp_ml_ml_proto_goTypes = nil
	file_newp_ml_ml_proto_depIdxs = nil
}
