// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: newp/ml/ml.proto

package ml1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Detector_ImageDetection_FullMethodName = "/grps.Detector/ImageDetection"
)

// DetectorClient is the client API for Detector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DetectorClient interface {
	ImageDetection(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error)
}

type detectorClient struct {
	cc grpc.ClientConnInterface
}

func NewDetectorClient(cc grpc.ClientConnInterface) DetectorClient {
	return &detectorClient{cc}
}

func (c *detectorClient) ImageDetection(ctx context.Context, in *DetectionRequest, opts ...grpc.CallOption) (*DetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetectionResponse)
	err := c.cc.Invoke(ctx, Detector_ImageDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DetectorServer is the server API for Detector service.
// All implementations must embed UnimplementedDetectorServer
// for forward compatibility.
type DetectorServer interface {
	ImageDetection(context.Context, *DetectionRequest) (*DetectionResponse, error)
	mustEmbedUnimplementedDetectorServer()
}

// UnimplementedDetectorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDetectorServer struct{}

func (UnimplementedDetectorServer) ImageDetection(context.Context, *DetectionRequest) (*DetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImageDetection not implemented")
}
func (UnimplementedDetectorServer) mustEmbedUnimplementedDetectorServer() {}
func (UnimplementedDetectorServer) testEmbeddedByValue()                  {}

// UnsafeDetectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DetectorServer will
// result in compilation errors.
type UnsafeDetectorServer interface {
	mustEmbedUnimplementedDetectorServer()
}

func RegisterDetectorServer(s grpc.ServiceRegistrar, srv DetectorServer) {
	// If the following call pancis, it indicates UnimplementedDetectorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Detector_ServiceDesc, srv)
}

func _Detector_ImageDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DetectorServer).ImageDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Detector_ImageDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DetectorServer).ImageDetection(ctx, req.(*DetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Detector_ServiceDesc is the grpc.ServiceDesc for Detector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Detector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grps.Detector",
	HandlerType: (*DetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ImageDetection",
			Handler:    _Detector_ImageDetection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "newp/ml/ml.proto",
}
