# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.grps.protos.detector_pb2 as detector__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in detector_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageDetection = channel.unary_unary(
                '/Detector/ImageDetection',
                request_serializer=detector__pb2.DetectionRequest.SerializeToString,
                response_deserializer=detector__pb2.DetectionResponse.FromString,
                _registered_method=True)


class DetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageDetection(self, request, context):
        """Единственный метод - детекция объектов на изображении
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageDetection,
                    request_deserializer=detector__pb2.DetectionRequest.FromString,
                    response_serializer=detector__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Detector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Detector', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Detector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Detector/ImageDetection',
            detector__pb2.DetectionRequest.SerializeToString,
            detector__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
