# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
from . import detector_pb2 as detector__pb2


class DetectorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ImageDetection = channel.unary_unary(
                '/grps.Detector/ImageDetection',
                request_serializer=detector__pb2.DetectionRequest.SerializeToString,
                response_deserializer=detector__pb2.DetectionResponse.FromString,
                )


class DetectorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ImageDetection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DetectorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ImageDetection': grpc.unary_unary_rpc_method_handler(
                    servicer.ImageDetection,
                    request_deserializer=detector__pb2.DetectionRequest.FromString,
                    response_serializer=detector__pb2.DetectionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'grps.Detector', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Detector(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ImageDetection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/grps.Detector/ImageDetection',
            detector__pb2.DetectionRequest.SerializeToString,
            detector__pb2.DetectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
