syntax = "proto3";
package grps;
option go_package = "sirius.ml.v1;ml1";

service Detector {
  rpc ImageDetection (DetectionRequest) returns (DetectionResponse);
}

message DetectionRequest {
  int64 query_id = 1;
  string dir_path = 2;
  repeated string targets = 3;
}

message DetectionResponse {
  int64 query_id = 1;
  string result_path = 2;
  bool success = 3;
  repeated InstanceInfo instance_info = 4; // [{"person": 3}, {"car": 2}]
  string error_message = 5;
  int32 total_objects = 6;
}

message InstanceInfo {
  string class_name = 1;
  float confidience = 2;
  // Bounding box: [x_min, y_min, x_max, y_max]
  repeated float bbox = 3;
}

