// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: newp/database/database.proto

package database1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          string                 `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_newp_database_database_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *CreateUserRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_newp_database_database_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          string                 `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRequest) Reset() {
	*x = CheckUserRequest{}
	mi := &file_newp_database_database_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRequest) ProtoMessage() {}

func (x *CheckUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRequest.ProtoReflect.Descriptor instead.
func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{2}
}

func (x *CheckUserRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *CheckUserRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type CheckUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserResponse) Reset() {
	*x = CheckUserResponse{}
	mi := &file_newp_database_database_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserResponse) ProtoMessage() {}

func (x *CheckUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserResponse.ProtoReflect.Descriptor instead.
func (*CheckUserResponse) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{3}
}

func (x *CheckUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckUserResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          string                 `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_newp_database_database_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteUserRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *DeleteUserRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_newp_database_database_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddNewAnswerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          string                 `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNewAnswerRequest) Reset() {
	*x = AddNewAnswerRequest{}
	mi := &file_newp_database_database_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNewAnswerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewAnswerRequest) ProtoMessage() {}

func (x *AddNewAnswerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewAnswerRequest.ProtoReflect.Descriptor instead.
func (*AddNewAnswerRequest) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{6}
}

func (x *AddNewAnswerRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *AddNewAnswerRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type AddNewAnswerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNewAnswerResponse) Reset() {
	*x = AddNewAnswerResponse{}
	mi := &file_newp_database_database_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNewAnswerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewAnswerResponse) ProtoMessage() {}

func (x *AddNewAnswerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewAnswerResponse.ProtoReflect.Descriptor instead.
func (*AddNewAnswerResponse) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{7}
}

func (x *AddNewAnswerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RequestOldAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Quantity      int64                  `protobuf:"varint,1,opt,name=Quantity,proto3" json:"Quantity,omitempty"`
	Flag          string                 `protobuf:"bytes,2,opt,name=Flag,proto3" json:"Flag,omitempty"`
	UserID        string                 `protobuf:"bytes,3,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOldAnswersRequest) Reset() {
	*x = RequestOldAnswersRequest{}
	mi := &file_newp_database_database_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOldAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOldAnswersRequest) ProtoMessage() {}

func (x *RequestOldAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOldAnswersRequest.ProtoReflect.Descriptor instead.
func (*RequestOldAnswersRequest) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{8}
}

func (x *RequestOldAnswersRequest) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *RequestOldAnswersRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *RequestOldAnswersRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type RequestOldAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestOldAnswersResponse) Reset() {
	*x = RequestOldAnswersResponse{}
	mi := &file_newp_database_database_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestOldAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestOldAnswersResponse) ProtoMessage() {}

func (x *RequestOldAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestOldAnswersResponse.ProtoReflect.Descriptor instead.
func (*RequestOldAnswersResponse) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{9}
}

func (x *RequestOldAnswersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestOldAnswersResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestDeletedAnswersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flag          string                 `protobuf:"bytes,1,opt,name=Flag,proto3" json:"Flag,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeletedAnswersRequest) Reset() {
	*x = RequestDeletedAnswersRequest{}
	mi := &file_newp_database_database_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeletedAnswersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeletedAnswersRequest) ProtoMessage() {}

func (x *RequestDeletedAnswersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeletedAnswersRequest.ProtoReflect.Descriptor instead.
func (*RequestDeletedAnswersRequest) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{10}
}

func (x *RequestDeletedAnswersRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *RequestDeletedAnswersRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *RequestDeletedAnswersRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestDeletedAnswersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestDeletedAnswersResponse) Reset() {
	*x = RequestDeletedAnswersResponse{}
	mi := &file_newp_database_database_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestDeletedAnswersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeletedAnswersResponse) ProtoMessage() {}

func (x *RequestDeletedAnswersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_newp_database_database_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeletedAnswersResponse.ProtoReflect.Descriptor instead.
func (*RequestDeletedAnswersResponse) Descriptor() ([]byte, []int) {
	return file_newp_database_database_proto_rawDescGZIP(), []int{11}
}

func (x *RequestDeletedAnswersResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_newp_database_database_proto protoreflect.FileDescriptor

const file_newp_database_database_proto_rawDesc = "" +
	"\n" +
	"\x1cnewp/database/database.proto\x12\bdatabase\";\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\tR\x04Flag\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\".\n" +
	"\x12CreateUserResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\":\n" +
	"\x10CheckUserRequest\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\tR\x04Flag\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"A\n" +
	"\x11CheckUserResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\";\n" +
	"\x11DeleteUserRequest\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\tR\x04Flag\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"=\n" +
	"\x13AddNewAnswerRequest\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\tR\x04Flag\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"0\n" +
	"\x14AddNewAnswerResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"b\n" +
	"\x18RequestOldAnswersRequest\x12\x1a\n" +
	"\bQuantity\x18\x01 \x01(\x03R\bQuantity\x12\x12\n" +
	"\x04Flag\x18\x02 \x01(\tR\x04Flag\x12\x16\n" +
	"\x06UserID\x18\x03 \x01(\tR\x06UserID\"I\n" +
	"\x19RequestOldAnswersResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12\x12\n" +
	"\x04Data\x18\x02 \x01(\fR\x04Data\"^\n" +
	"\x1cRequestDeletedAnswersRequest\x12\x12\n" +
	"\x04Flag\x18\x01 \x01(\tR\x04Flag\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\x12\x12\n" +
	"\x04Data\x18\x03 \x01(\fR\x04Data\"9\n" +
	"\x1dRequestDeletedAnswersResponse\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage2\xf3\x03\n" +
	"\bDatabase\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.database.CreateUserRequest\x1a\x1c.database.CreateUserResponse\x12D\n" +
	"\tCheckUser\x12\x1a.database.CheckUserRequest\x1a\x1b.database.CheckUserResponse\x12G\n" +
	"\n" +
	"DeleteUser\x12\x1b.database.DeleteUserRequest\x1a\x1c.database.DeleteUserResponse\x12K\n" +
	"\n" +
	"AddNewData\x12\x1d.database.AddNewAnswerRequest\x1a\x1e.database.AddNewAnswerResponse\x12Z\n" +
	"\x0fRequestOldDatas\x12\".database.RequestOldAnswersRequest\x1a#.database.RequestOldAnswersResponse\x12f\n" +
	"\x13RequestDeletedDatas\x12&.database.RequestDeletedAnswersRequest\x1a'.database.RequestDeletedAnswersResponseB\x1eZ\x1csirius.database.v1;database1b\x06proto3"

var (
	file_newp_database_database_proto_rawDescOnce sync.Once
	file_newp_database_database_proto_rawDescData []byte
)

func file_newp_database_database_proto_rawDescGZIP() []byte {
	file_newp_database_database_proto_rawDescOnce.Do(func() {
		file_newp_database_database_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_newp_database_database_proto_rawDesc), len(file_newp_database_database_proto_rawDesc)))
	})
	return file_newp_database_database_proto_rawDescData
}

var file_newp_database_database_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_newp_database_database_proto_goTypes = []any{
	(*CreateUserRequest)(nil),             // 0: database.CreateUserRequest
	(*CreateUserResponse)(nil),            // 1: database.CreateUserResponse
	(*CheckUserRequest)(nil),              // 2: database.CheckUserRequest
	(*CheckUserResponse)(nil),             // 3: database.CheckUserResponse
	(*DeleteUserRequest)(nil),             // 4: database.DeleteUserRequest
	(*DeleteUserResponse)(nil),            // 5: database.DeleteUserResponse
	(*AddNewAnswerRequest)(nil),           // 6: database.AddNewAnswerRequest
	(*AddNewAnswerResponse)(nil),          // 7: database.AddNewAnswerResponse
	(*RequestOldAnswersRequest)(nil),      // 8: database.RequestOldAnswersRequest
	(*RequestOldAnswersResponse)(nil),     // 9: database.RequestOldAnswersResponse
	(*RequestDeletedAnswersRequest)(nil),  // 10: database.RequestDeletedAnswersRequest
	(*RequestDeletedAnswersResponse)(nil), // 11: database.RequestDeletedAnswersResponse
}
var file_newp_database_database_proto_depIdxs = []int32{
	0,  // 0: database.Database.CreateUser:input_type -> database.CreateUserRequest
	2,  // 1: database.Database.CheckUser:input_type -> database.CheckUserRequest
	4,  // 2: database.Database.DeleteUser:input_type -> database.DeleteUserRequest
	6,  // 3: database.Database.AddNewData:input_type -> database.AddNewAnswerRequest
	8,  // 4: database.Database.RequestOldDatas:input_type -> database.RequestOldAnswersRequest
	10, // 5: database.Database.RequestDeletedDatas:input_type -> database.RequestDeletedAnswersRequest
	1,  // 6: database.Database.CreateUser:output_type -> database.CreateUserResponse
	3,  // 7: database.Database.CheckUser:output_type -> database.CheckUserResponse
	5,  // 8: database.Database.DeleteUser:output_type -> database.DeleteUserResponse
	7,  // 9: database.Database.AddNewData:output_type -> database.AddNewAnswerResponse
	9,  // 10: database.Database.RequestOldDatas:output_type -> database.RequestOldAnswersResponse
	11, // 11: database.Database.RequestDeletedDatas:output_type -> database.RequestDeletedAnswersResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_newp_database_database_proto_init() }
func file_newp_database_database_proto_init() {
	if File_newp_database_database_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_newp_database_database_proto_rawDesc), len(file_newp_database_database_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_newp_database_database_proto_goTypes,
		DependencyIndexes: file_newp_database_database_proto_depIdxs,
		MessageInfos:      file_newp_database_database_proto_msgTypes,
	}.Build()
	File_newp_database_database_proto = out.File
	file_newp_database_database_proto_goTypes = nil
	file_newp_database_database_proto_depIdxs = nil
}
